baseURL = "https://blog.maxhu.dev/"
languageCode = "en-us"
title = "blog.maxhu.dev"
theme = "hello-friend-ng"
enableGitInfo = true

[[menu.main]]
identifier = "blog"
name       = "Blog"
url        = "/posts"

[params.Logo]
logoText = "Max Hu's Blog"

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
